name: Main
on:
  push:
    branches: [ $default-branch, init ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  unit_testing:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest]

    steps:  
      - uses: actions/checkout@v2

      - name: Set up env
        run: |
          pip install poetry==1.1.6
          poetry install

      - name: Unit testing
        run: |
          poetry run pytest
  
  publish: 
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up env
        run: |
          pip install poetry
          poetry install

      - name: Build
        run: poetry build

      - name: Publish on Pypi
        with: 
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          echo $PYPI_USER
          poetry publish -u $PYPI_USER -p PYPI_PASSWORD 
