name: Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2

      - name: Set up env
        run: |
          pip install poetry==1.1.6
          poetry install

      - name: Unit testing
        run: |
          poetry run pytest

  code_quality:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up env
        run: |
          pip install poetry==1.1.6
          poetry install
      - name: Code formating
        run: poetry run black --check dyndns_updater/
          
      - name: Linting
        run: poetry run pylint --fail-under=7 dyndns_updater/

  
  publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up env
        run: |
          pip install poetry==1.1.6
          poetry install

      - name: Build
        run: poetry build

      - name: Publish on Pypi
        env: 
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          echo $PYPI_USER
          poetry publish -u "$PYPI_USER" -p "$PYPI_PASSWORD" 
